### ISSUE TITLE
Exclude fields

### ISSUE THREAD

**Issue by 9bits** [philmander/browser-bunyan#29]
Hi! My log is getting quite cluttered. Is there a way to exclude fields? 

Like `v`, `count`, `time`? 

I read this discussion (https://github.com/trentm/node-bunyan/issues/52) about excluding fields for `bunyan`, but I wasn't successful for `browser-bunyan`. Some help would be appreciated. Thanks so much.

**Comment by philmander** [comment]
What log stream(s) are you using?

**Comment by philmander** [comment]
Anyway, whatever stream you are using, you can always decorate an existing stream to delete log fields. For example:

```js
class RemoveFieldsStreamDecorator {
     constructor(stream, toDelete = [ 'v', 'count', 'time' ]) {
          this.stream = stream;
          this.toDelete = toDelete;
    }
    
    write(rec) {
         this.toDelete.forEach(f => { delete rec[f] });
         this.stream.write(rec);
    }
}

const formattedStream = new RemoveFieldsStreamDecorator(new ConsoleFormattedStream(());
```

(this is actually a bad example though, because `ConsoleFormattedStream`, specifically, uses `rec.time` and would break. In which case, you'd have to make a more customized stream)

**Comment by 9bits** [comment]
Thanks!
I'm using ServerStream, btw.
